### ISSUE TITLE
Create tagged releases

### ISSUE THREAD

**Issue by jsejcksn** [ubersl0th/markdown#1]
That way users can import a specific version of the module and the API won't potentially change and break their app. Using [semver](https://semver.org/) values for tag versions (e.g. `v0.1.0`, `v1.1.2`, etc.) is ideal.

See:
- https://deno.land/manual/linking_to_external_code#how-do-i-import-a-specific-version-of-a-module
- https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by ubersl0th** [comment]
Sorry for the late answer, took an extra long vacation this summer because of COVID.

I'll try to get on this when I have the time and energy.
Feel free to help me out with whatever you need/want with a PR or two 👍

**Comment by jsejcksn** [comment]
In order to help out with this, one would need to be a collaborator of the repository because only those with write permissions can create releases.

Releases don't have anything to do with PRs. Check out the links I posted to understand more.

**Comment by ubersl0th** [comment]
I've invited you as collaborator if you wish, I've also created an initial release, 1.0.0.
I plan to merge #4 (frontmatter support) and create another release for this; 2.0.0. (breaking change)
Any thoughts?

**Comment by jsejcksn** [comment]
@ubersl0th Thank you for the invitation. I'll look at that and #4 soon when I can focus on it.

Release: 👍 — however, you might want to create another release as `v1.0.0` (prefixed with a literal `v`). This is the common convention for semver git tagging—you don't have to follow this pattern, but it's the norm for software releases. ([I think many Deno repos are learning about the importance of release tagging right now.](https://github.com/denolib/ms/issues/5#issuecomment-654030900))

**Comment by ubersl0th** [comment]
@jsejcksn 
About the versioning; The semver spec states that vX.Y.Z is not semver but X.Y.Z is, but I observed that vX.Y.Z is commonplace.
I was wondering how the tag reflects in import statement / dependency management?
I'd prefer to use @X.Y.Z over @vX.Y.Z as one would with package.json for example.

**Comment by jsejcksn** [comment]
> About the versioning; The semver spec states that vX.Y.Z is not semver but X.Y.Z is, but I observed that vX.Y.Z is commonplace.

That's right. Sounds like you did the research!

> I was wondering how the tag reflects in import statement / dependency management?


In Deno, it looks like this:

```ts
import {Marked} from 'https://deno.land/x/markdown@v1.0.0/mod.ts';
```

or

```ts
import {Marked} from 'https://raw.githubusercontent.com/ubersl0th/markdown/v1.0.0/mod.ts';
```

etc.

> I'd prefer to use @X.Y.Z over @vX.Y.Z as one would with package.json for example.

Nothing is preventing you from using either format that you mentioned (or both). It's ultimately up to you, as git tags are just strings, but there are many reasons people choose to follow conventions: expectations of users, expectations of tag string parsing software, etc.

I don't know the full history, but I imagine that git tag versions are prefixed with a `v` precisely because the tags can be any string, and the `v` prefix indicates to a parser that it's a version number and not any other arbitrary string.

**Comment by ubersl0th** [comment]
Okey, as of now there are tags for both `v1.0.0` and `1.0.0`, but going forward I'll use the `vX.Y.Z` notation since it is the norm.

**Comment by jsejcksn** [comment]
[Great timing](https://deno.land/posts/registry2)
