### ISSUE TITLE
Front-matter support

### ISSUE THREAD

**Issue by dnswd** [ubersl0th/markdown#2]
Metadata can be useful, and I think it would be an excellent addition to the project. I'm already implementing front-matter using [Deno's standard library](https://deno.land/std/encoding/yaml.ts) in my fork repo, and it doesn't seem to affect much performance.

The only change is the parse() function returns a Javascript object instead of a string, because the content and the metadata has to be separate. Thoughts on this?

**Comment by ubersl0th** [comment]
Sorry for the late answer, took an extra long vacation this summer because of COVID.

I agree that it would be a good addition, and if you've already implemented it, open up a PR if you like and I'll have a look at it 👍

**Comment by ubersl0th** [comment]
Issue solved as of merged PR #4
